version: "3.7"

services:
  auth:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8181:8080
    environment:
      - quarkus.datasource.url=jdbc:postgresql://auth-db:5432/auth
  auth-db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=sarah
      - POSTGRES_PASSWORD=connor